// AUTO-GENERATED by scripts/generate-icon-data.mjs — DO NOT EDIT BY HAND.
// Source: icons/svg/*.svg (and featured-error/*.svg)
// Run `pnpm run gen:icon-data` to refresh.

export * from './icon-data.js';
export * from './featured-icon-data.js';
