/**
 * AegisX Design System — Theme export
 *
 * Serialises the current Tweaks panel state into a paste-ready bundle:
 *
 *   tokens.css                        — :root declarations for every --ax-*
 *                                       custom property currently applied
 *   aegisx-material-theme.scss        — mat.define-theme({...}) + density
 *   aegisx-material-bridge.scss       — --mat-sys-* aliases
 *   aegisx-component-overrides.scss   — per-MDC tweaks (only for properties
 *                                       that differ from defaults)
 *   tokens.json                       — Tokens Studio format snapshot
 *   README.md                         — quick-start instructions
 *
 * Output: a single combined .scss file with `// === filename ===` section
 * markers so consumers can split or paste into styles.scss as-is.
 *
 * No external dependency, no ZIP — keeps export deterministic.
 * Depends on: _tweaks.js (reads localStorage[`aegisx-ds-tweaks`]).
 */
(function () {
  'use strict';

  const LS_KEY = 'aegisx-ds-tweaks';
  const AX_TOKEN_PREFIX = '--ax-';

  const BRAND_LABEL = {
    indigo:'Indigo (Material)', blue:'Blue', emerald:'Emerald', cyan:'Cyan',
    purple:'Purple', rose:'Rose', amber:'Amber', slate:'Slate'
  };
  const FONT_FAMILY = {
    plex:    "'IBM Plex Sans Thai', 'IBM Plex Sans', 'Noto Sans Thai', system-ui, sans-serif",
    noto:    "'Noto Sans Thai', 'IBM Plex Sans Thai', system-ui, sans-serif",
    inter:   "'Inter', 'Noto Sans Thai', system-ui, sans-serif",
    sarabun: "'Sarabun', 'Noto Sans Thai', system-ui, sans-serif"
  };

  function getState() {
    try { return Object.assign({}, JSON.parse(localStorage.getItem(LS_KEY) || '{}')); }
    catch (e) { return {}; }
  }

  function snapshotTokens() {
    const root = document.documentElement;
    const cs = getComputedStyle(root);
    // Pull every --ax-* from both inline style + linked stylesheets.
    const names = new Set();
    for (let i = 0; i < root.style.length; i++) {
      const n = root.style[i];
      if (n.startsWith(AX_TOKEN_PREFIX)) names.add(n);
    }
    for (const sheet of document.styleSheets) {
      let rules;
      try { rules = sheet.cssRules; } catch (e) { continue; } // cross-origin
      if (!rules) continue;
      for (const rule of rules) {
        if (rule.type === 1 /* STYLE_RULE */ && rule.selectorText && rule.selectorText.includes(':root')) {
          for (let i = 0; i < rule.style.length; i++) {
            const n = rule.style[i];
            if (n.startsWith(AX_TOKEN_PREFIX)) names.add(n);
          }
        }
      }
    }
    const tokens = {};
    [...names].sort().forEach(n => {
      const v = cs.getPropertyValue(n).trim();
      if (v) tokens[n] = v;
    });
    return tokens;
  }

  function tokensCss(tokens, state) {
    const lines = [];
    lines.push('/* AegisX Design System — tokens snapshot');
    lines.push(` * Exported: ${new Date().toISOString()}`);
    lines.push(` * Theme:    ${state.theme || 'light'}`);
    lines.push(` * Brand:    ${state.brand || 'indigo'} (${BRAND_LABEL[state.brand] || BRAND_LABEL.indigo})`);
    lines.push(` * Density:  ${state.density || 'comfortable'}`);
    lines.push(` * Radius:   ${state.radius ?? 6}px`);
    lines.push(` * Font:     ${state.fontFamily || 'plex'} @ ${state.fontSize ?? 14}px`);
    lines.push(' */');
    lines.push(':root {');
    for (const [name, value] of Object.entries(tokens)) {
      lines.push(`  ${name}: ${value};`);
    }
    lines.push('}');
    return lines.join('\n');
  }

  function materialTheme(state) {
    const density = state.density === 'compact' ? -2
                  : state.density === 'spacious' ? 0
                  : -1;
    const fontFamily = FONT_FAMILY[state.fontFamily || 'plex']
      .replace(/^'|'$/g, '').split(',')[0].trim();
    return `// aegisx-material-theme.scss — generated by Tweaks export
// Drop into src/styles/ and @use first, before any app styles.

@use '@angular/material' as mat;

@include mat.core();

$aegisx-light-theme: mat.define-theme((
  color: (
    theme-type: light,
    primary:   mat.$azure-palette,    // override by --mat-sys-primary in bridge
    tertiary:  mat.$green-palette,
    use-system-variables: true,
  ),
  typography: (
    brand-family: '${fontFamily}',
    plain-family: '${fontFamily}',
    regular-weight: 400,
    medium-weight:  500,
    bold-weight:    600,
  ),
  density: (
    scale: ${density},   // ${density === -2 ? 'compact · ~32px rows' : density === -1 ? 'default · ~40px rows' : 'spacious · ~48px rows'}
  ),
));

$aegisx-dark-theme: mat.define-theme((
  color: (
    theme-type: dark,
    primary:   mat.$azure-palette,
    tertiary:  mat.$green-palette,
    use-system-variables: true,
  ),
  density: (scale: ${density}),
));

:root {
  @include mat.all-component-themes($aegisx-light-theme);
  @include mat.system-level-colors($aegisx-light-theme);
  @include mat.system-level-typography($aegisx-light-theme);
}

[data-theme='dark'] {
  @include mat.all-component-colors($aegisx-dark-theme);
  @include mat.system-level-colors($aegisx-dark-theme);
}`;
  }

  function readText(url) {
    return fetch(url, { cache: 'no-cache' }).then(r => r.ok ? r.text() : '');
  }

  function componentOverrides(state) {
    const r = Number(state.radius ?? 6);
    const fs = Number(state.fontSize ?? 14);
    return `// aegisx-component-overrides.scss — generated by Tweaks export
// Per-MDC property tweaks that differ from the repo default. Imported
// after aegisx-material-bridge.scss so Material components pick up the
// exact radii and sizing your Tweaks state expressed.

:root {
  // Corner shape — driven by current Tweaks radius slider (${r}px)
  --mdc-filled-button-container-shape:      ${r}px;
  --mdc-outlined-button-container-shape:    ${r}px;
  --mdc-text-button-container-shape:        ${r}px;
  --mdc-protected-button-container-shape:   ${r}px;
  --mdc-outlined-text-field-container-shape: ${r}px;
  --mdc-filled-text-field-container-shape:  ${r}px;
  --mdc-dialog-container-shape:             ${r + 6}px;
  --mdc-snackbar-container-shape:           ${r}px;
  --mdc-plain-tooltip-container-shape:      ${r}px;
  --mdc-chip-container-shape:               ${r + 10}px;
  --mat-menu-container-shape:               ${r}px;

  // Typography base
  font-size: ${fs}px;
}`;
  }

  function tokensJson(tokens, state) {
    const obj = {
      $schema: 'https://design-tokens.org/draft-format/',
      $description: 'AegisX Tweaks export — generated ' + new Date().toISOString(),
      $metadata: {
        theme: state.theme || 'light',
        brand: state.brand || 'indigo',
        density: state.density || 'comfortable',
        radiusPx: Number(state.radius ?? 6),
        fontFamilyStack: FONT_FAMILY[state.fontFamily || 'plex'],
        fontSizePx: Number(state.fontSize ?? 14)
      },
      tokens: {}
    };
    for (const [name, value] of Object.entries(tokens)) {
      obj.tokens[name.slice(2)] = { $value: value, $type: guessType(name, value) };
    }
    return JSON.stringify(obj, null, 2);
  }

  function guessType(name, value) {
    if (/-(color|bg|background|border|text|surface|primary|brand|error|warning|success|info)(-|$)/.test(name)) return 'color';
    if (/#[0-9a-f]{3,8}/i.test(value) || /^(rgb|hsl|oklch|color-mix)/.test(value)) return 'color';
    if (/-(size|space|spacing|height|width|gap|radius|pad|inset)(-|$)/.test(name)) return 'dimension';
    if (/-(shadow|elevation)(-|$)/.test(name)) return 'shadow';
    if (/-(duration|delay)(-|$)/.test(name)) return 'duration';
    if (/-(easing|cubic)(-|$)/.test(name)) return 'cubicBezier';
    if (/-(weight|leading|tracking)(-|$)/.test(name)) return 'other';
    return 'other';
  }

  function readme(state) {
    const r = Number(state.radius ?? 6);
    const fs = Number(state.fontSize ?? 14);
    return `# AegisX — Custom theme bundle

Exported: ${new Date().toISOString()}
Based on @aegisx-platform/design-system

## Tweaks snapshot
- Theme:   ${state.theme || 'light'}
- Brand:   ${state.brand || 'indigo'} (${BRAND_LABEL[state.brand] || 'Indigo'})
- Density: ${state.density || 'comfortable'}
- Radius:  ${r}px
- Font:    ${state.fontFamily || 'plex'} @ ${fs}px
- Focus ring: ${state.focusRing || 'blue'}
- Elevation: ${state.elevation || 'soft'}

## Quick start

1. Save each section (marked by \`// === filename ===\`) into its own file under \`src/styles/\`.
2. Add to your root \`styles.scss\` (order matters):

   \`\`\`scss
   // 1. Token values
   @import './styles/tokens.css';

   // 2. Material M3 theme (density, typography, palettes)
   @use './styles/aegisx-material-theme';

   // 3. Bridge --ax-* → --mat-sys-*
   @use './styles/aegisx-material-bridge';

   // 4. Per-MDC shape / sizing tweaks
   @use './styles/aegisx-component-overrides';

   // 5. Your app styles
   @use './styles/app';
   \`\`\`

3. In \`index.html\` load the active font if you changed it (Noto / Inter / Sarabun):

   \`\`\`html
   <link href="https://fonts.googleapis.com/css2?family=${(state.fontFamily || 'plex') === 'plex' ? 'IBM+Plex+Sans+Thai' : (state.fontFamily === 'noto' ? 'Noto+Sans+Thai' : state.fontFamily === 'inter' ? 'Inter' : 'Sarabun')}:wght@400;500;600;700&display=swap" rel="stylesheet">
   \`\`\`

4. Set the theme attribute on \`<html>\` to switch palettes:

   \`\`\`html
   <html data-theme="${state.theme || 'light'}" data-density="${state.density || 'comfortable'}">
   \`\`\`

## What's in each file

| File | Purpose |
|---|---|
| tokens.css | All \`--ax-*\` custom properties resolved to the current Tweaks state |
| aegisx-material-theme.scss | \`mat.define-theme({...})\` with density + typography |
| aegisx-material-bridge.scss | Aliases \`--mat-sys-*\` → \`--ax-*\` so Material picks up AegisX values |
| aegisx-component-overrides.scss | Per-MDC shape + sizing overrides derived from current radius / font |
| tokens.json | Tokens Studio format snapshot (Figma sync) |

All Material components render with AegisX colors automatically because \`--mat-sys-*\` resolves through the bridge to \`--ax-*\`.
`;
  }

  async function generateBundle() {
    const state = getState();
    const tokens = snapshotTokens();

    // Try to pull canonical bridge from the served stylesheet so it matches repo exactly.
    let bridgeText = '';
    const tryPaths = ['../tokens/scss/aegisx-material-bridge.scss', './tokens/scss/aegisx-material-bridge.scss'];
    for (const p of tryPaths) {
      // eslint-disable-next-line no-await-in-loop
      bridgeText = await readText(p);
      if (bridgeText) break;
    }
    if (!bridgeText) {
      bridgeText = '/* aegisx-material-bridge.scss not fetched — see @aegisx-platform/design-system source. */';
    }

    const sections = [
      ['README.md', readme(state)],
      ['tokens.css', tokensCss(tokens, state)],
      ['aegisx-material-theme.scss', materialTheme(state)],
      ['aegisx-material-bridge.scss', bridgeText.trim()],
      ['aegisx-component-overrides.scss', componentOverrides(state)],
      ['tokens.json', tokensJson(tokens, state)]
    ];

    const bundle = sections.map(([name, body]) =>
      `// =============================================================================\n` +
      `// === ${name}\n` +
      `// =============================================================================\n\n` +
      body + '\n'
    ).join('\n');

    return bundle;
  }

  function downloadBlob(filename, text) {
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  async function exportTheme(btn) {
    const state = getState();
    const original = btn.textContent;
    btn.disabled = true;
    btn.textContent = 'Building…';
    try {
      const bundle = await generateBundle();
      const brand = state.brand || 'indigo';
      const density = (state.density || 'comfortable').slice(0, 3);
      const date = new Date().toISOString().slice(0, 10);
      downloadBlob(`aegisx-theme-${brand}-${density}-${date}.scss`, bundle);
      btn.textContent = '✓ Downloaded';
    } catch (e) {
      console.error('[aegisx:export-theme]', e);
      btn.textContent = '✗ Failed — see console';
    } finally {
      setTimeout(() => { btn.textContent = original; btn.disabled = false; }, 1600);
    }
  }

  function mountButton() {
    const panel = document.getElementById('ax-tweaks');
    if (!panel) return;
    const footer = panel.querySelector('.ax-tweaks__footer');
    if (!footer || footer.querySelector('[data-ax-tw="export"]')) return;

    const btn = document.createElement('button');
    btn.type = 'button';
    btn.dataset.axTw = 'export';
    btn.textContent = 'Export theme';
    btn.style.cssText = 'all:unset;cursor:pointer;display:inline-block;padding:4px 12px;margin:6px 0 2px;' +
      'background:var(--ax-brand-default);color:var(--ax-brand-inverted,#fff);' +
      'border-radius:var(--ax-radius-md);font-family:var(--ax-font-mono);font-size:10px;' +
      'font-weight:600;letter-spacing:0.04em;text-transform:uppercase;text-align:center;';
    btn.addEventListener('click', () => exportTheme(btn));

    // Insert above the "Live preview · saved to localStorage · reset" line.
    footer.parentNode.insertBefore(btn, footer);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mountButton);
  } else {
    // _tweaks.js mounts the panel DOM on DOMContentLoaded too; schedule after it.
    setTimeout(mountButton, 0);
  }
})();
